### ISSUE TITLE
Create a file mode filter to convert unix octal values to deciaml

### ISSUE THREAD

**Issue by ieugen** [Masterminds/sprig#109]
Hello, 

The title contains a very specific description but the tooling could be generic. 
We would like a file mode filter that can convert from unix octal permissions 0755 to decimal. The reason being that json does not support octal and it makes writing and maintaining charts quite cumbersome.

See https://github.com/helm/helm/issues/4378#issuecomment-407900416 for use case. 

Thanks,

**Comment by Dean-Coakley** [comment]
I'd like to take a go at implementing this, if someone could advise me on implementation specifics, or confirm such a feature could be merged that would be great! :)

**Comment by ieugen** [comment]
That wold be awesome. Please make a PR or a proposal. The implementation should be straight forward and similar to other filters.

**Comment by Dean-Coakley** [comment]
Just an update that I've started working on this. Code should work, just need to write some unit tests.

* Added toDecimal func in `numeric.go` that takes an interface{} and returns an int64
* If octal conversion fails returns 0

Let me know if you have some thoughts here

**Comment by mattfarina** [comment]
@Dean-Coakley Sorry for the slow reply. If you're still up for it please consider continuing the work. I would accept it.
