### ISSUE TITLE
Add function for generating dhparams?

### ISSUE THREAD

**Issue by krancour** [Masterminds/sprig#11]
In #10 @technosophos said:

> I have been thinking of adding some crypto functions to sprig for use with public key cryptography use cases.

I'd actually love if sprig supported generation of 1024 bit dhparams.  This would be tremendously useful to anyone, for instance, using github.com/helm/helm to manage Nginx or other web servers.

fwiw, generating _2048_ bit dhparams would be lunacy because it takes soooo long.  But what would we think about 1024 bit dhparams?

This might be crazy.

**Comment by technosophos** [comment]
This could definitely be useful. I will get to it when I have some time.

**Comment by krancour** [comment]
This is pretty stale and I don't know that the impetus for something like this is there anymore. The related issue that prompted this was closed three years ago... I'm going to close this one as well.
