### ISSUE TITLE
Feature request: Kebab Case function

### ISSUE THREAD

**Issue by josdotso** [Masterminds/sprig#113]
```
kebabcase "helloWorld" 
```
would both produce `hello-world`, similar to how `camelcase` and `snakecase` work.

**Comment by Ilyes512** [comment]
Kebabcase had been adder to the depency xstrings that spring already uses for kebab and camel casing. It easy to add and I will make a pr in a few. Just wondering what to do with documentation. I will first add it and see what’s next.

**Comment by mattfarina** [comment]
Closing as the PR is merged.
