### ISSUE TITLE
Feature Request: Have a "slim" version, without dependencies outside stdlib

### ISSUE THREAD

**Issue by andreynering** [Masterminds/sprig#114]
Thanks for building this lib! I really like it, but I'd like it even more if it haven't any dependency (outside the standard library)

Some of the current dependencies are to allow functions I don't care at all on templates, like UUID generation

For others, the following Go proverb applies:

> "A little copying is better than a than a little dependency"
>
> Rob Pike

For example, the `xstrings` package is imported just because of two functions

### Proposal

Have a `github.com/Masterminds/sprig/slim` package that have all the functions that doesn't require importing external libraries

**Comment by mattfarina** [comment]
>  "A little copying is better than a than a little dependency"
>   Rob Pike

This doesn't take into account software licenses. When you copy you need to comply with those.

> I'd like it even more if it haven't any dependency (outside the standard library)

What is the underlying use case for liking it with fewer dependencies? What is the need and why does it exist?

**Comment by andreynering** [comment]
@mattfarina 

> This doesn't take into account software licenses. When you copy you need to comply with those.

You have a point here. Maybe we shouldn't copy functions from other packages (unless pretty trivial). But we can still have the option of not importing them.

> What is the underlying use case for liking it with fewer dependencies? What is the need and why does it exist?

It's not a requirement or a necessity, I just prefer to keep things slim if possible. [Importing Sprig today requires importing at least another 6 packages](https://github.com/Masterminds/sprig/blob/master/glide.lock), mostly which I don't need. I hope this list doesn't grow more.

**Comment by mattfarina** [comment]
I think you illustrated the crux of things when you said...

> I just prefer 

This issue is a bit about preference. I understand and respect yours. This was just built with a different preference. Without a technical or user value justification I don't see us making this change. Can you make a technical of user value justification?

**Comment by andreynering** [comment]
- Smaller binary size;
- Less noise while managing dependencies (on go.mod, etc);
- Smaller chance of something breaking due changes in any of these libs.

I think more developers usually check how many dependencies a lib has before adopting it. Too many for a small lib and you have a red flag.

That's it, but if you disagree with it, feel free to close the issue. I'll think about maintaining my own fork, though.

**Comment by andreynering** [comment]
So, I just forked sprig into [slim-sprig](https://github.com/go-task/slim-sprig).

As a result, 6 dependencies are not required anymore to use Sprig, and I got a ~22-23% reduction on Task's binary size.

**Comment by mattfarina** [comment]
Since there is a fork with slimmed down features and we aren't planning on doing that here I'm going to close this issue. Thanks for the suggestion and the fork working to handle this.

**Comment by andreynering** [comment]
@mattfarina If you ever change idea and decide to bring to the main repository, let me know.
