### ISSUE TITLE
Silently omitting errors

### ISSUE THREAD

**Issue by nrvnrvn** [Masterminds/sprig#115]
There are cases when errors are not handled but it could be useful for debugging compilation errors. See [1](https://github.com/Masterminds/sprig/blob/77bb58b7f5e10889a1195c21b9e7a96ee166f199/defaults.go#L65), [2](https://github.com/Masterminds/sprig/blob/77bb58b7f5e10889a1195c21b9e7a96ee166f199/dict.go#L83), [3](https://github.com/Masterminds/sprig/blob/77bb58b7f5e10889a1195c21b9e7a96ee166f199/date.go#L74)

In some cases it is pretty much all right to return default-*ish* values silently but in some cases it would be useful to fail and print the error message.

Proposal:
- extend the existing API and introduce {func}E versions of some funcs like it is done here https://github.com/spf13/cast

**Comment by mattfarina** [comment]
Pull requests welcome for this.
