### ISSUE TITLE
add a string utility for pluralizing

### ISSUE THREAD

**Issue by arschles** [Masterminds/sprig#12]
It would be a nice utility to be able to pluralize a string. For example, `{{ pluralize 1 "anchovy" "anchovies" }}` would return `anchovy`, but ``{{ pluralize 2 "anchovy" "anchovies" }}` would return `anchovies`

**Comment by technosophos** [comment]
Great idea.

**Comment by technosophos** [comment]
I'm trying to figure out what the right order of params would be. Is it more likely to be: `{{len foo | pluralize "anchovy" "anchovies"}}`?

Optionally, we could do `{{pluralize "1 thinger", "%d thingers" $len}}` and do the substitution for the user.

**Comment by technosophos** [comment]
Okay, that last part was a bad idea, since it would then _require_ a `%d`, which is silly.

```
	functions_test.go:391: Expected 'cheese', got 'cheese%!(EXTRA int=1)'
```
