### ISSUE TITLE
feature request: `seq`

### ISSUE THREAD

**Issue by bacongobbler** [Masterminds/sprig#124]
bash has a command called `seq` that takes a number and returns a sequence of numbers up to and including that number, starting from 1.

You can also define the intervals using two additional (optional) arguments: `seq $BEGIN $INTERVAL $END`. For example, `seq 0 1 3` would return the list `0 1 2 3`, whereas `seq 0 2 10` would return `0 2 4 6 8 10`.

I think a function that performs similar to `seq` would be a great enhancement to sprig, as one could use it in templates via the following:

```
It's as easy as {{ seq 3 }}!
```

Docs for `seq` can be found here: http://tldp.org/LDP/abs/html/extmisc.html

For the time being, you can use `list 1 2 3` to achieve the same effect.

ref: https://github.com/helm/helm/issues/4876

**Comment by Dean-Coakley** [comment]
Just wanted to let you know I've started work on this feature. 
So far I think it works pretty well but the code is not nice, not used to programming so heavily to interfaces. So I'll try improve before opening a PR.

Hopefully creating `seq.go` is correct
