### ISSUE TITLE
substr unexpected result

### ISSUE THREAD

**Issue by stephenmoloney** [Masterminds/sprig#130]
#### issue:

unexpected result for substr

```
{{ print (substr 4 4 "hello world") }}
```
expected ```o wor```

instead got `0`

Am I missing something ?

**Comment by Dean-Coakley** [comment]
Documentation is incorrect.

### substr is documented as:
```
Get a substring from a string. It takes three parameters:
* start (int)
* length (int)
* string (string)
```

### But the behaviour is defined as:
```
Get a substring from a string. It takes three parameters:
* start (int)
* end (int)
* string (string)
```

So afaik `{{ print (substr 4 9 "hello world") }}` would yield your expected output

**Comment by stephenmoloney** [comment]
@Dean-Coakley Thanks - all clear now. I did a workaround this for my use case but I'll keep this in mind for next time.
