### ISSUE TITLE
Support Go modules

### ISSUE THREAD

**Issue by rarkins** [Masterminds/sprig#145]
The `kebabcase` function [relies on xstrings.ToKebabCase](https://github.com/Masterminds/sprig/blob/9f8fceff796fb9f4e992cd2bece016be0121ab74/functions.go#L132) which was released in their v1.2.0. Unfortunately Go modules falls back to the minimum version of xstrings, which is v1.0.0, so it fails. For Go modules users of this library I think you need a way of indicating v1.2.0 as the minimum for `huandu/xstrings`, and the best way for this is a `go.mod` here.

**Comment by mattfarina** [comment]
v3 now uses `go.mod`
