### ISSUE TITLE
Release tag inconsistency 2.19.0 vs v2.19.0

### ISSUE THREAD

**Issue by etiennetremel** [Masterminds/sprig#146]
In the previous release the "v" prefix was included in the tag, the latest release doesn't include it which seem to break module import.

Would it be possible to re-tag 9f8fceff796fb9f4e992cd2bece016be0121ab74 as v2.19.0?

https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

**Comment by etiennetremel** [comment]
Actually it isn't breaking go modules, just inconsistency.

**Comment by mattfarina** [comment]
Strange as I would have expected it to break go modules. In case some other tool has an issue I create a v2.19.0 tag that also points to the same commit. Let's hope that doesn't break anything.
