### ISSUE TITLE
provide a deepCopy() function

### ISSUE THREAD

**Issue by multi-io** [Masterminds/sprig#149]
Without deepCopy(), Helm will be unusable for certain fairly simple tasks because of #120 : 
You cannot repeatedly use merge with the same "base" dict as the first argument unless you can tolerate that that dict will be modified every time. deepCopy() would avoid this.

**Comment by bitsofinfo** [comment]
Please! would be great if this was added

**Comment by nfedyk** [comment]
+1, this would be helpful.

**Comment by bmudda** [comment]
+1

**Comment by InvictusMB** [comment]
Adding deepCopy() alone is not enough. merge and mergeOverwrite must also use deepCopy under the hood for nested dictionaries/lists. Because even when you create a new dictionary for dist argument is still leaks references of nested dictionary/list references from sources.

**Comment by multi-io** [comment]
> Adding deepCopy() alone is not enough. merge and mergeOverwrite must also use deepCopy under the hood for nested dictionaries/lists. Because even when you create a new dictionary for dest argument it still leaks references of nested dictionary/list references from sources into the dest.

I guess my take on that was if you had deepCopy(), you could use it on the arguments to merge before calling merge.

**Comment by InvictusMB** [comment]
@multi-io 
Technically yes, you could guard all the arguments individually. However, `merge` has to do this for you. I don't see its current behavior as practical.
I'm OK with `merge` mutating the first argument (although, I would call it `extend` in this case), but it currently has a potential to mutate any argument passed into it and also introduce unexpected links between data structures. See my [example](https://github.com/Masterminds/sprig/issues/120#issuecomment-519439250) in #120.
This kind of side effects is not something you expect from a templating helper.

**Comment by mattfarina** [comment]
#188 captures the details affecting `mergeOverwrite`. This needs to be fixed.

A `deepCopy` function would be a great feature addition. Because #188 captures the bug I'll mark this one for the feature request.

**Comment by multi-io** [comment]
> @multi-io
> Technically yes, you could guard all the arguments individually. However, `merge` has to do this for you. I don't see its current behavior as practical.

I guess I'd rather not modify `merge`, even if it has unusual semantics, as it's already out there and in widespread use.

**Comment by mattfarina** [comment]
deep copying was just merged in so closing.

**Comment by bitsofinfo** [comment]
When will this be released?
