### ISSUE TITLE
Please add a simple "get" function for Dicts

### ISSUE THREAD

**Issue by bitsofinfo** [Masterminds/sprig#151]
Would be great to just be able to do

```
{{ $theKeysValue := get $mydict $somekey }}
```

**Comment by bitsofinfo** [comment]
i need this due to dynamic key names

**Comment by InvictusMB** [comment]
@bitsofinfo 
It is possible to express your case as `{{ $theKeysValue  := pick $mydict $somekey | values | first }}`

**Comment by bitsofinfo** [comment]
yes i'm aware and that is what i'm doing, but I think this would be a good feature to add as it is not all that intuitive to someone new to this library.

**Comment by mattfarina** [comment]
PRs are welcome to add this.
