### ISSUE TITLE
Allow trunc to accept negative lengths

### ISSUE THREAD

**Issue by mholt** [Masterminds/sprig#167]
I'd like to propose that `trunc` accept negative lengths to keep that many characters at the _end_ of a string:

```
trunc -5 "hi, world"
// "world"
```

Maybe implemented like this:

```go
if length < 0 && len(input)+length > 0 {
	return input[len(input)+length:]
}
if length >= 0 && len(input) > length {
	return input[:length]
}
return input
```

Willing to submit a PR if you're OK with the idea. Or if this is already possible using some clever trick just tell me and I'll be happy. :smile:

**Comment by Dean-Coakley** [comment]
@mholt Thanks very much for including the implementation example, was very helpful! 😄

**Comment by mholt** [comment]
Great! Thanks for the PR!
