### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by mholt** [Masterminds/sprig#207]
It would be nice to have a function to generate a random number in a certain range:

```
{{ randInt 12 30 }}
```

This would generate a random number in the range [12,30).

Then I could generate random strings of random length:

```
{{ randInt 8 256 | randAscii }}
```

This has utility when padding encrypted transmissions so patterns of length can't be as easily deciphered.

**Comment by kochurovro** [comment]
@mholt Hi. We have done this issue. Kindly can you review it? 
https://github.com/Masterminds/sprig/pull/211

**Comment by mholt** [comment]
Woo you beat me to it!
