### ISSUE TITLE
Feature Request: dict function, nestedValue

### ISSUE THREAD

**Issue by andye2004** [Masterminds/sprig#227]
I have had to write a pretty horrible function in a helm chart, see [here for issue](https://github.com/helm/helm/issues/5180), and [here for ugly hack](https://github.com/helm/helm/issues/5180#issuecomment-566544808).

It would be good if this could be done via sprig and I'm happy to do a PR for this feature if it would be accepted into the library?

**Comment by AndyKilpatrick** [comment]
An alternative solution (if the deep dive fix is too complex, or the current behavious is needed for some other reason) might be a new "and" function which evaluates left-to-right but doesn't evaluate arguments one a False is found .  Then, helm template could use code like this (still more verbose but not too bad):
{{ if and (and .Values.obj .Values.obj.subobj) .Values.obj.subobj.field }} .Values.obj.subobj.field{{ else }}"default value"{{ end }}
This fails with the standard "and" as all arguments are evaluated.

**Comment by vladfr** [comment]
Hi,

Found a nice solution to this, which works in go templates [and has been documented by the fine folks at Hugo](https://gohugo.io/functions/merge/).

You can create a map with defaults, and then use `merge` to have them set. Who knew?

```
{{- $default_params := dict "access" "proxy" "type" "prometheus" "basicAuth" "false" "version" 1 -}}
      {{- range .Values.grafana.datasources }}
      {{- $p := merge $default_params . -}}
      - access: {{ $p.access | quote }}
      [...]
      {{- end }}

```

This works nicely, I've just tested with a small Grafana wrapper chart using Helm 3. 

I believe this solution can close this issue.

**Comment by nyarly** [comment]
It would be really nice to have something like https://ruby-doc.org/core-2.3.0_preview1/Hash.html#method-i-dig though. @vladfr's example could be rewritten as something like
```go
{{- range .Values.grafana.datasources }}
- access: {{ .access | default "proxy" | quote }}
- type: {{ .type | default "prometheus" | quote }}
   # [...]
{{- end }}
```
