### ISSUE TITLE
Ability to add keys to dict variable 

### ISSUE THREAD

**Issue by sbezverk** [Masterminds/sprig#23]
Currently there is no way to add any key to already instantiated variable. It makes building large dictionaries difficult, as all key needs to be specified within a single {{ with }} command.
It would be great to be able to build dict variable by adding 1 key at the time.

example:
{{ $env := dict "blah-1" $blah-1 }}
{{ $env := dict "blah-2" $blah-2 }}
resulting $env having two pairs of keys.

**Comment by kfox1111** [comment]
+1.

maybe something like
{{ $env := dict "blah-1" $blah-1 }}
{{ $env := dict-update $env "blah-2" $blah-2 }}

**Comment by technosophos** [comment]
Oops... forgot to close this back when we added `set`
