### ISSUE TITLE
why don t you simply use map[string]interface{} ?

### ISSUE THREAD

**Issue by mh-cbon** [Masterminds/sprig#29]
Hi,

Why do you type juggle with template.FuncMap and html.FuncMap in the public functions instead of using only map[string]interface{}  ?

Also, in [this](https://github.com/Masterminds/sprig/blob/master/functions.go#L222), i suspect it is not working on a copy, compare with this [playground](https://play.golang.org/p/vrb3dbo0gK)

btw, i noticed a typo [at](https://github.com/Masterminds/sprig/blob/master/functions.go#L212) => `tpl := template.New("foo").Funcs(sprig.FuncMap())`

**Comment by technosophos** [comment]
Ideally so that they could return different sets of functions depending on the renderer, though that never really happened in the codebase.
