### ISSUE TITLE
new function: exactMatch 

### ISSUE THREAD

**Issue by dmpe** [Masterminds/sprig#292]
Hi, can we add please also `exactMatch` - similar to regexMatch ?

Much appreciated. Thanks

**Comment by felipecrs** [comment]
Hm... would not this be the same as wraping the content of `regexMatch` pattern into `^$` like:

```
{{ regexMatch "^my-regex$" "my-text" }}
```

?

**Comment by dmpe** [comment]
I have already found a different approach, and not needing it anymore. Though many thanks for the suggestion!
