### ISSUE TITLE
sprig: many functions could be variadic.

### ISSUE THREAD

**Issue by robpike** [Masterminds/sprig#3]
The function Add, for example, takes two arguments. Why not take an arbitrary number? The language is prefix so it's easy to have multiple arguments:

{{Add 2 3 4}}

func Add(nums []int) int

You could make them even more general by accepting any numeric type and converting as necessary under the covers, but that's a lot more work.

**Comment by technosophos** [comment]
Good idea. We'll work on this.

**Comment by hobti01** [comment]
Since append is not variadic, is there a method to concatenate two arrays/slices?
This would be nice: `{{ range (append .arrayA .arrayB) }}`

This is possible with strings but a bit awkward and fragile:
`{{ range (printf "%s!%s" (.arrayA|join "!") (.arrayB|join "!") | splitList "!") }}`

**Comment by mattfarina** [comment]
I'm closing as these functions appear to be variadic already. I looks like this was implemented sometime in the past 4 years.

@hobti01 You should be able to concat multiple lists with the `concat` template function.
