### ISSUE TITLE
Add support for generating htpasswd hash

### ISSUE THREAD

**Issue by TimJones** [Masterminds/sprig#32]
A function that can generate the `htpasswd` type hash from username & password would be great. In Kubernetes Helm charts, this would help in configuring basic auth for ingress resources.

**Comment by technosophos** [comment]
Can you point me to some documentation? I'm not sure what the hashing algo is that it uses.

**Comment by Kamshak** [comment]
If anyone comes here from google, the algorithms are a bit of a mess: 
https://httpd.apache.org/docs/2.4/misc/password_encryptions.html
lots of apache specific stuff in C, not sure if anyone want's to port that over.

Easy way to get around it for helm charts and nginx is to use plain text to store the pw: 
```
auth: {{ (print "{PLAIN}" (index .Values.apiKey)) | b64enc | quote }}
``` 
Not cool to store the PWs like this but it's in a kubernetes secret so i guess it's ok? Suppose for proper auth you wouldn't use basic auth anyway

**Comment by Tim-Schwalbe** [comment]
Can you explain where it is stored in plain text? because the secret is base64 encoded

**Comment by sanderploegsma** [comment]
@Kamshak Nginx indeed seems to support plain text passwords in the passwd file. However, when I create a Kubernetes secret that contains `foo:bar` (base64 encoded) the Nginx Controller doesn't accept these credentials. If I use `htpasswd` to encrypt `bar` it works.

Are you sure that your approach should work for the Nginx Ingress controller?

**Comment by Kamshak** [comment]
Hey, I'm not running the app that required this anymore so I'm not sure if
it still works (but I guess it should unless something in nginx changed). I
think the key to making it work was to have that {PLAIN} in there.


Sander Ploegsma <notifications@github.com> schrieb am Di., 10. Dez. 2019,
14:47:

**Comment by j-zimnowoda** [comment]
Would it be possible implement third argument for `sprig htpasswd`, so I can provide htpasswd related arguments?

e.g.:
```
{{ htpasswd .Values.username .Values.password 'nBC 10' }}
```
