### ISSUE TITLE
Feature request: Add isset

### ISSUE THREAD

**Issue by josegonzalez** [Masterminds/sprig#327]
It would be great have an `isset` function so we can do stuff like:

```
{{ if isset . "clock_cronitor_id" }}{{ .clock_cronitor_id }}{{ end }}
```

If this is okay, I'm happy to work on an MR to try to build it into sprig.

**Comment by rhansen** [comment]
Doesn't the following already do what you want?

```
{{ if hasKey . "clock_cronitor_id" }}{{ .clock_cronitor_id }}{{ end }}
```
