### ISSUE TITLE
ceil and floor functions

### ISSUE THREAD

**Issue by devth** [Masterminds/sprig#34]
It's not clear what happens with `div` if the result is not an int. Need to be able to explicitly control if it gets rounded up or down.

Example use case: calculate the min number of nodes required to form a quorum, i.e. `{{ replicas | div 2 | ceil}}`. I'm not sure this will work even if we had ceil/floor functions because I'm guessing `div` is already performing an implicit ceil or floor.

I suppose if `div` is already doing an implicit floor then we can do `{{ replicas | div 2 | add1}}`.

Thoughts?

**Comment by devth** [comment]
Update: actually my example doesn't work because `div` is diving `2 / replicas` which will always be 0. Need a way to flip the argument order. 🤔 

The alternative of `mul 0.5` doesn't work either because `0.5 gets turned into 0`.

**Comment by notxcain** [comment]
In case someone faces the same problem: `{{ div replicas 2 | add 1 }}` does the trick
