### ISSUE TITLE
Typo in release 2.10.0 Changelog.

### ISSUE THREAD

**Issue by chrishalbert** [Masterminds/sprig#390]
I noticed this while reading through release notes 2.10.0, but `initial` is spelled `intial`. Unless of course we are aiming to get the `int` like value :P Ok, terrible joke, but here's a [PR ](https://github.com/Masterminds/sprig/pull/391) to fix the [line in question](https://github.com/Masterminds/sprig/blob/master/CHANGELOG.md?plain=1#L310).

**Comment by mattfarina** [comment]
This change was merged so closing the issue.
