### ISSUE TITLE
What is the repository status is?

### ISSUE THREAD

**Issue by ivankatliarchuk** [Masterminds/sprig#403]
Hello. Last release was in November 2022. Any plans to cut a fresh release?

**Comment by mattfarina** [comment]
A fresh release is coming soon.

This repo is typically maintained in passes that normally happen one to a few times per year. While that has not happened for over a year, another pass is now being done. Expect a release soon.

I will close this issue after a release.

**Comment by mattfarina** [comment]
A new release just went out.
