### ISSUE TITLE
Clarification: nil vs empty string

### ISSUE THREAD

**Issue by scottrigby** [Masterminds/sprig#53]
Hello!

While reviewing recent charts PRs (example: https://github.com/kubernetes/charts/pull/2004), I see this interesting pattern:
```yaml
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
```

The explanation is:
```yaml
  ## mariadb data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
```

My question was, since the template-rendered YAML will either be a storage class name, an empty string (to disable dynamic provisioning), or not set at all, can't we just do this instead?
```yaml
  ## mariadb data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to empty string "", this disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: ""
```

Then the template logic could be simplified to:
```yaml
{{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
```

But this would only work if an empty string is different from not set (`nil`) when checking `if .Values.some.value` in go template. Can someone help clarify this for me, or point to the relevant part of the docs? I seem to not be able to find this info.

Thanks!

**Comment by scottrigby** [comment]
OK, I found the relevant helm issue: https://github.com/kubernetes/helm/issues/2600

But just checking here, is there really no way for sprig to differentiate the difference between `nil` and `""` (empty string) in a template? If not, would that be a desirable PR?

**Comment by technosophos** [comment]
Wow. That issue actually helped me nail down an issue I was seeing in a local PVC! Ha!

Okay, so an `{{ if $value }}` will check for both `""` and `nil`, considering either one to be an "empty value". There is also the `empty` function, which essentially behaves the same way.

It might be nice to be able to test whether something is `nil` and possibly empty (`{{ if isNil $foo }}`). I don't think we have a way of checking that. Maybe `eq $foo nil` would work... I've never tried.

Does that answer your question, or am I misunderstanding.

**Comment by mattfarina** [comment]
@technosophos If something is a string, isn't the initialized value on a struct `""` instead of `nil`? How would you get the `nil` state without the template engine complaining about the missing field?

I imagine I'm missing something which is why I ask.

**Comment by jkroepke** [comment]
Found a solution `{{ kindIs "invalid" $value }}`

**Comment by mattfarina** [comment]
@scottrigby @technosophos Here's an example of the previous comment... https://play.golang.org/p/9yJW5iGT4qa

When I looked at this in the past I'd not thought of this. Thanks @jkroepke

**Comment by scottrigby** [comment]
Love it 😄

**Comment by thesuperzapper** [comment]
> Found a solution `{{ kindIs "invalid" $value }}`

@jkroepke While this solution might work, I imagine there are other cases where the "kind" of something might be "invalid" without it being `nil`.

I think better option is to use a direct equality check against `nil`:

```
{{ eq $value nil }}
```


PS: the reason that the kind of `nil` equals "invalid" is actually because `nil` does not have a type in Go, because it is a ["predeclared identifier"](https://go.dev/ref/spec#Predeclared_identifiers).
