### ISSUE TITLE
Allow indent to skip first line

### ISSUE THREAD

**Issue by calind** [Masterminds/sprig#54]
We are using `indent` function in helm templates to generate `yaml` files. In lots of places we need to indent stuff, but that breaks template indentations (see below).

```yaml
  resources:
{{ .Values.resources | indent 4 }}
```

Jinja `indent` filter allows skipping the first line. I think that would be useful so that we can write templates as the following snippet which allows keeping the natural indentation in template files:

```yaml
  resources:
    {{ .Values.resources | indent 4 true }}
```

**Comment by keitwb** [comment]
To anyone who is interested in this functionality, you can achieve the same thing by piping the result of the indent to `trim`:

```yaml
    resources:
    {{ .Values.resources | indent 4 | trim }}
```

This will remove the whitespace from the first line, but the indentation of the template block will make up for it.

**Comment by mattfarina** [comment]
Because this can be accomplished with pipelines and existing functions I'm going to go ahead and close this. Thanks for the suggestion and the way of doing it today.
