### ISSUE TITLE
last doesn't behave has expected

### ISSUE THREAD

**Issue by robinbryce** [Masterminds/sprig#59]
I'm trying to split a string into parts and take the last element.
~~~~
{{regexSplit "/src/" "foo/src/bar" -1 | last}}
~~~~

Expecting "bar" but getting

~~~~
 executing "" at <last>: wrong type for value; expected []interface {}; got []string
~~~~

As a work around I have done this:
~~~~     
{{with $my:=regexSplit "/src/" "foo/src/bar" -1}}
     {{index $my 1}} # Can't do arithmetic in templates :-(
{{end}}
~~~~

Which feels unreasonably cumbersome and still not quite what I wanted.

**Comment by mattfarina** [comment]
@robinbryce without touching on the technical issue here (I'll leave the implementation discussion to @technosophos), it's often considered a breaking of separation of concerns to have logic (like arithmetic) in templates. Is there a reason you're not doing that in application code?

**Comment by robinbryce** [comment]
Sure, thats a sound principle. In this instance I can't see a way to achieve it. Permitting simple arithmetic is an escape hatch. The 'application' here is go-task (which isn't under my control). My preference is to use 'last' which is functional and robust. In the absence of that, I would have no problem with `index len($my)-1`. Which, while not ideal, is at least less brittle than a hard coded index?

**Comment by BarDweller** [comment]
I suspect the reason here is the same as the broader issue I raised in Issue #63, methods expecting lists are expecting the type `[]interface` but methods returning lists (`regexSplit` included) are not returning that type. So it's tricky to build pipelines with the provided functions because they disagree on types.

**Comment by mattfarina** [comment]
@BarDweller That makes a lot of sense. Thanks for pointing that out.

@technosophos I think we need to use a little reflection magic to get these to merge. What do you think of something like https://play.golang.org/p/1AYZ0t_tAb. Note, I don't really like the panic and am open to other ways of handling the type error in a backwards compatible manner.

**Comment by technosophos** [comment]
@mattfarina Yeah, I don't object to that at least for the more common types.

**Comment by mattfarina** [comment]
I'll work on these this week.
