### ISSUE TITLE
stringify function

### ISSUE THREAD

**Issue by jchauncey** [Masterminds/sprig#6]
So I need a template function that will wrap double quotes around a provided string. So something like this: `{{ stringify "this string" }}`. Right now go templates will not enclose the string with quotes so I have to do something like this: `"{{"this string"}}". Which looks weird when Im using go templates to output configuration files.

**Comment by technosophos** [comment]
I'm thinking that a function called `quote` would be good for that. Should I add a `squote` version for single quotes, too?

So `{{quote "Hello"}}` would produce `"hello"` in the destination text.

Does that sound right?

**Comment by jchauncey** [comment]
yeah
