### ISSUE TITLE
sprig: add max and min

### ISSUE THREAD

**Issue by moorereason** [Masterminds/sprig#7]
Just a suggestion:  deprecate `biggest` and add `max` and `min` funcs.

**Comment by technosophos** [comment]
Why deprecate? It's easy enough to add max and min, though.

**Comment by moorereason** [comment]
Because `biggest` is ugly.  :wink:  No big deal, though.

**Comment by technosophos** [comment]
Done. Added `min`, aliased `max` and `biggest` to the same function, deprecated `biggest`.
