### ISSUE TITLE
sprig playground ?

### ISSUE THREAD

**Issue by lfundaro** [Masterminds/sprig#71]
Hey folks, do you think it makes sense to have a golang playground with sprig functions already loaded ? I think it will be nice to get a better feel of the functions that one can use, and how they behave.

**Comment by mattfarina** [comment]
A big issue is, who will host it? Any ideas?

**Comment by drewwells** [comment]
hosting is cheap. what would the playground look like? Definitely would be nice to add a helm default that populated `{{ .Release }}` variable.

**Comment by mattfarina** [comment]
Two things....

1) You can pull sprig into the Go playground, use it, and share it. For an example see https://play.golang.org/p/8pFRbRuWycl

2) Hosting is cheap but someone needs to pay for it. And put in the time to keep it secure and up. This isn't a corporate run project but rather the personal project of some people. They would have to pay for hosting out of their own pocked and put in the time on their personal time.

Closing this as it is possible to do with the Go playground.

**Comment by dgk** [comment]
found it https://repeatit.io/
