### ISSUE TITLE
Add support for URL handling

### ISSUE THREAD

**Issue by calind** [Masterminds/sprig#72]
A very useful addition to the Path function class would be functions dealing with URLs, like extracting domain, path or a query argument from a URL.

**Comment by mattfarina** [comment]
Can you provide a use case?

If the URL is known in code a [URL instance](https://golang.org/pkg/net/url/#URL) could be passed in and the parts are accessible as strings. I'm trying to consider a case when someone would want to use this.

**Comment by mattfarina** [comment]
This was added in #170
