### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by sfrek** [Masterminds/sprig#75]
Hello, 

my go version is: `go version go1.8.3 linux/amd64`

When I want to use your library I get next message:

```
# github.com/Masterminds/sprig
../../Masterminds/sprig/crypto.go:35: multiple-value uuid.NewV4() in single-value context
```

Checking _crypto.go_ file I have seen this:

```go
// uuidv4 provides a safe and secure UUID v4 implementation
func uuidv4() string {
	return fmt.Sprintf("%s", uuid.NewV4())
}
```

But `uuid.NewV4()'  return two values, the `UUID` and an `error`

I've send you one pull request https://github.com/Masterminds/sprig/pull/74.

Regards

**Comment by saeidakbari** [comment]
Hi 
Please accept pull request #74 as soon as possible.
many of our container got error during build because of this
Best regards

**Comment by flaccid** [comment]
Also suffering..

**Comment by sleaze** [comment]
Also hitting this, and sufferinggg...........................................

**Comment by distorhead** [comment]
Fix for go-get users:

```
go get -v github.com/satori/go.uuid
git -C $GOPATH/src/github.com/satori/go.uuid checkout v1.2.0
go get -v <your-app>
```

**Comment by sfrek** [comment]
@distorhead thanks.

Yep, I have dived deeper and then closed https://github.com/Masterminds/sprig/pull/74.

**Comment by JHoelzel** [comment]
Another quick fix for this on Windows is to just open up the src of github.com/satori/go.uuid and change the current branch over the integrated Git management to v1.2. After that everything builds as usual =)
