### ISSUE TITLE
Use newer version of mergo package

### ISSUE THREAD

**Issue by seaneagan** [Masterminds/sprig#77]
sprig is currently locked to version 0.2.2 of mergo in glide.lock.  Version 0.3.0 added [this fix](https://github.com/imdario/mergo/commit/0b8c27e3f9b30e65dda6bb23ba86340b0f6b59a7) for merging slices correctly (deeply).  Any chance of updating to 0.3.0?  Here is a [comparison](https://github.com/imdario/mergo/compare/0.2.2...0.3.0) between those versions for reference.

**Comment by mattfarina** [comment]
@seaneagan We'd be up for the change. In addition to a straight update a test case that fails under the old method but passes in the new one would be useful for sprig. That would document as well as test the situation.

Are you up for the pull request?

**Comment by mattfarina** [comment]
Sprig is not using the latest version of mergo.
