### ISSUE TITLE
issue with new version of go.uuid

### ISSUE THREAD

**Issue by quochungndvt** [Masterminds/sprig#78]
https://github.com/Masterminds/sprig/blob/master/crypto.go#L35
need change from: 
return fmt.Sprintf("%s", uuid.NewV4())
=>
return fmt.Sprintf("%s", uuid.Must(uuid.NewV4()))

**Comment by zwopir** [comment]
I just about to create a PR for this. There are two possible solutions for the problem:
 - use `uuid.Must(nuuid.NewV4()))` (see OP)
 - return an error message as string. This approach is used in the other functions in `crypto.go`, so I would stick to this solution.

Any thoughts about it?

**Comment by kevinmichaelchen** [comment]
@zwopir `uuid.Must` panics on error. Is there a reason that's not okay or sufficient?

**Comment by mattfarina** [comment]
The change to `go.uuid` is not released, yet. Once a release version of the library is out it should be pretty easy to upgrade to it.

**Comment by mattfarina** [comment]
sprig moved to the google uuid library and this issue should be gone now.
