### ISSUE TITLE
Add "dict" function

### ISSUE THREAD

**Issue by sparkprime** [Masterminds/sprig#8]
This is suggested here:

http://stackoverflow.com/questions/18276173/calling-a-template-with-several-pipeline-parameters/18276968#18276968

It'd stand beside the tuple function, which is the equivalent for arrays.

This is really useful for writing templates that are encapsulated and don't depend on the full dot value.

**Comment by technosophos** [comment]
Good idea. I'm not particularly fond of syntax this will require (e.g. even number of arguments), but I can see why it'd be useful.
