### ISSUE TITLE
bug in uuidv4()

### ISSUE THREAD

**Issue by sl4mmer** [Masterminds/sprig#82]
`../../Masterminds/sprig/crypto.go:35:37: multiple-value uuid.NewV4() in single-value context
`

**Comment by sl4mmer** [comment]
#83

**Comment by lastcoolnameleft** [comment]
Any update?

**Comment by mattfarina** [comment]
Thanks for filing this issue. This is a duplication of #78. I'm going to close this to consolidate the conversation to one place.
