### ISSUE TITLE
Documentation missing lots of functions

### ISSUE THREAD

**Issue by phemmer** [Masterminds/sprig#84]
[The documentation](https://godoc.org/github.com/Masterminds/sprig) doesn't mention many of the [functions which are actually available](https://github.com/Masterminds/sprig/blob/master/functions.go):

* `regex*`
* `b32*`
* `fail`
* `genCA`/`genSelfSignedCert`/`genSignedCert`
* `merge`
* `toJson`/`toPrettyJson`
more probably

**Comment by mattfarina** [comment]
Many of these are documented. For example, the regex ones are documented on https://masterminds.github.io/sprig/strings.html. It appears the top level index page does not reference these and that could use to be updated.

Thanks for catching this.

**Comment by mattfarina** [comment]
Every function is now documented.
